title: Daria Navrotska  # your name (or website title) here
logo: "/images/Photo-Daria Navrotska â€“ small.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br><br>
  Passionate about transforming complex data into valuable insights.
  <br><br>
  <a href="https://www.linkedin.com/in/daria-navrotska/">View My LinkedIn Profile</a> 

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
